### ISSUE TITLE
Issue during the Dockerbuild / can't cd to /ghost/blog/versions/1.0.0/core/server/adapters/storage

### ISSUE THREAD

**Issue by pascalandy** [mmornati/docker-ghostblog#2]
Just tried it and got this issue.

Step 22/28 : RUN cd /ghost/blog/versions/1.0.0/core/server/adapters/storage &&   git clone https://github.com/mmornati/ghost-cloudinary-store.git &&   cd ghost-cloudinary-store &&   git checkout update_ghost_1.0.0 &&   npm install
 ---> Running in 85046572f48c
/bin/sh: 1: cd: can't cd to /ghost/blog/versions/1.0.0/core/server/adapters/storage

Thanks for sharing your setup!

**Comment by GregaVrbancic** [comment]
I have solved this issue by uncommenting this line https://github.com/mmornati/docker-ghostblog/blob/master/Dockerfile#L39 and adding -p flag to mkdir command.

**Comment by mmornati** [comment]
I think the problem was related to the version (I could be updated in the meanwhile). With the new Dockerbuild script, the version is hardcoded into the file and we won't have this problem anymore.
