### ISSUE TITLE
Allow to override Mail object

### ISSUE THREAD

**Issue by sr229** [mmornati/docker-ghostblog#26]
this would allow the Mail object to be configured in the container to use any mailing service

**Comment by sr229** [comment]
It seems that ghost also allows config by config vars, so you should investigate a little about that

**Comment by mmornati** [comment]
There is a mount point to do what you want with the configuration (config.override.json).
You can then create your personal config.json file with the mail server you prefer and add it as volume to your Docker container. It will be used a configuration file. 

We did in this way cause it was impossible to allow any possible configuration into the  docker image via variables or anything else.
But you can do what you want in a simple way.
