### ISSUE TITLE
[BRAINSTORMING] Optimise the multi-stage Dockerfile build further more

### ISSUE THREAD

**Issue by pascalandy** [mmornati/docker-ghostblog#27]
This is the idea.

### 4 stages

1. base
2. dependencies
3. build
4. release

Inspired by:  https://blog.hasura.io/an-exhaustive-guide-to-writing-dockerfiles-for-node-js-web-apps-bbee6bd2f3c4

```
# ---- Base Node ----
FROM node:carbon AS base
# Create app directory
WORKDIR /app

# ---- Dependencies ----
FROM base AS dependencies  
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
# install app dependencies including 'devDependencies'
RUN npm install

# ---- Copy Files/Build ----
FROM dependencies AS build  
WORKDIR /app
COPY src /app
# Build react/vue/angular bundle static files
# RUN npm run build

# --- Release with Alpine ----
FROM node:8.9-alpine AS release  
# Create app directory
WORKDIR /app
# optional
# RUN npm -g install serve
COPY --from=dependencies /app/package.json ./
# Install app dependencies
RUN npm install --only=production
COPY --from=build /app ./
#CMD ["serve", "-s", "dist", "-p", "8080"]
CMD ["node", "server.js"]

```

**Comment by mmornati** [comment]
Cool. But I don't get the need of the base step with only the app directory creation... If then it is created even in all other steps. The base can maybe the step you named dependencies?

But yeah... I think it is easy to understand the docker file in this way and we can maybe gain some other bytes :)

**Comment by pascalandy** [comment]
I didn't give it a real thought yet. But as a template, I think it makes sense. 

Don't know yet if it applies to our project thought :p If it sparks something in our heads cool. Else just drop it :p

**Comment by sr229** [comment]
This kind of layout is what BaaS/PaaS services like Heroku uses to build containers for their apps with, in the context of this repository, this would help readability in my opinion.

**Comment by sr229** [comment]
I think we can further clean the Dockerfile for readability since @mmornati suggested using ``USER`` for commands that require to be ran on ``node`` on this [Pull Request](https://github.com/mmornati/docker-ghostblog/pull/31)
