### ISSUE TITLE
Version 1.21.1 works, but there is an error during the build

### ISSUE THREAD

**Issue by pascalandy** [mmornati/docker-ghostblog#29]
Something is not clean here. https://github.com/mmornati/docker-ghostblog/pull/28

## under step 4

https://travis-ci.org/mmornati/docker-ghostblog/builds/340304432#L616

![screen shot 2018-02-11 at 8 14 25 pm](https://user-images.githubusercontent.com/6694151/36081082-3d55d1bc-0f68-11e8-8e3c-a876f50fe227.jpg)

## QA

The image works normally

![screen shot 2018-02-11 at 8 11 57 pm](https://user-images.githubusercontent.com/6694151/36081087-47c517fc-0f68-11e8-9c4c-836ed542b719.jpg)

## Next step

Testing with node 6

**Comment by pascalandy** [comment]
UPDATE

I got the same error using node6-alpine

https://travis-ci.org/mmornati/docker-ghostblog/jobs/340307121#L600

I propose to continue to use node:8 and keep an eye on this bug.

**Comment by mmornati** [comment]
The issue is related to python during the npm package install. I think it is not included into the alpine image we are using.
We can maybe change the image for the standard node 1 for the build stage and use the alpine only into the final one

**Comment by pascalandy** [comment]
Not following when you say

> standard node 1

**Comment by sr229** [comment]
@pascalandy the error happens because the dependency requires Python, which in relevant terms, you need a custom builder image that has Python and Node.js both installed. This can be hotpatched by `apk add python python3` afaik.

**Comment by pascalandy** [comment]
Cool, make sense from the PR you submitted. Will test on my side.
